pipeline {
    agent any
    parameters {
        choice(
            name: 'action', 
            choices: ['apply', 'destroy'], 
            description: 'Choose the terraform action to perform'
            )
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ChetanPinjarkar/jenkins-terraform-fun.git'
            }
        }
        stage('Terraform init') {
            steps {
                dir('vm_provision') {
                    sh 'terraform init'                
                }
            }
        }
        stage('Terraform validate') {
            steps {
                dir('vm_provision') {
                    sh 'terraform validate'
                }
            }
        }
        stage('Terraform Plan') {
            when {
                expression { params.action == 'apply' }
            }
            steps {
                dir('vm_provision') {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage('Approval') {
            steps {
                input message: "Confirm terraform ${params.action}?",
                ok: "Yes, proceed"
            }
        }
        stage('Terraform Apply or Destroy') {
            steps {
                dir('vm_provision') {
                    script {
                        if (params.action == 'apply') {
                            sh 'terraform apply -auto-approve tfplan'
                        } else {
                            sh 'terraform destroy -auto-approve'
                        }
                    }
                }
            }
        }
    }
}
